* Celpip対策
** Task1
*** 対策
- 論理と発音の両方で評価される模様。[[https://secure.paragontesting.ca/InstructionalProducts/PracticeTest5/OPT5/View/61ac8ebf-9983-4f4a-a6a3-0578712bb48e][Set 5, Practice1]]の7-8RESPONSEは発音が明瞭であったが、結婚を祝う発言であり、プロポーズの仕方の回答になっていない。
  それでも評価は7-8である。
  
*** CELPIP-General Practice Tests, Set 4, Practice Test 1
**** 修正答案
There are two grocery stores in our town. The first one is Target, and the second one is Sakura Mart.
I suggest you go to the Target. The main reason is that you can buy tasty and inexpensive foods there.
They are not only delicious but also healthy because most of them are organic foods.
There are many sellers, and they are helpful. They are willing to help you if you cannot find what you want to buy.
If you live near the Target, you should go there.
On the other hand, Sakura Mart is a small grocery store.
The prices of Sakura Mart's products are comparatively higher than the prices of Target.
The staff members look busy, and you cannot expect them to help you.
They don't arrange products well. It takes time to find the products that you are looking for.
*** CELPIP-General Practice Tests, Set 4, Practice Test 2
**** 答案
Speaking now, Sorry, I think you have a several options to solve this problem.
Now, first, you should use public transit, right? Like a train bus to get our new office.
The second option is you can ask you. I think you should try to ask your parents to buy a car and to go to our office.
And that this is the second options.
Another option is you should work another side job to.
Well, I mean part you should do and another part of time job to get money into by a new And your car.
This is the third options now. I think you should In our new office is near.
And the big stations. So I think you can use a public tool and plants it.
Although you have to work a walk to go to our office but it is very inexpensive approach. So I recommend you first options.
*** CELPIP-General Practice Tests, Set 5, Practice Test 1
**** 答案
Ground of, I think you should take her to Our restaurant, and I have a dinner.
And now give a little wedding ring to how and Propose.
I think it is a usual but it is a modest way to make success.
And so I recommend you this approach.
If you are not interested in this approach,
you should take trip with her and prepare for some surprise to make her happy and weighing her to marriage.
Mary with you. This is a second approach. The third is You just, I'll
You when you if you leave with her and stay home together and ask her to marry you, this is the third approach.
I can propose. I think the first option is better.
**** 修正答案
I think you should take her to a memorable place where you and she have been before.
You have been dating her for 2years, which is a long time.
You should make use of the memories you both share and take advantage of the time you have spent together.
If there is a restaurant that you both visited before, consider taking her there and proposing to her.
Of course, it is essential to choose a restaurant that she likes.
You should propose to her after all the dishes have been served except for dessert because food and alcohol can make people feel generous.
This could increase the chances of her accepting your proposal.
You should order as many dishes and alcohol as she want, but you should not have them too much to convince her to accept your proposal.
** Task2
*** 対策
- 問いに応えていない回答にならないように、回答の内容ではなく回答すべき項目をメモに書きだしてはどうか。
*** CELPIP-General Practice Tests, Set 4, Practice Test 1
**** 答案
Now, I will talk about a chat GPT and without is a generative AI,
and that I can people use it by saying, put typing a text into a browser and the generated
AI returns a text and to respond. What I you are the people, right? And I changed my life.
For example, I actually do exercise my English speaking text and skills and writing skills
by using chat GPT and without asking other in English speakers to correct,
my English sentences by using this chart GPT I can Efficiency, polish my English.
**** 批評
Chat GPT以前の生活が不明なので、生活をどのように変えたか分かりにくい。以前と以後の対比を明確にした回答のようがいい。

**** 修正答案
Tell me the grammatical errors in the text.
I will talk about Chat GPT. It is generative AI.
People type text on a web browser, and Chat GPT responds.
It has changed my life.
I use Chat GPT to correct some of my English texts.
Before I used Chat GPT, I asked colleagues or English teachers to correct some of my texts.
It was a time-consuming task.
After I use Chat GPT, I write a text on a web browser and have it corrected.
I can save time by using Chat GPT.
Apart from that, I use Chat GPT instead of Google to find the information I need.
Chat GPT sometimes can answer questions that I could not solve using Google.

*** CELPIP-General Practice Tests, Set 4, Practice Test 2
**** 答案
I will talk about the experience that I voted a sheriff and built myself. Built it myself.
I bought I a shell at Ikea and ordered it.
You'll I hear to this sheriff by truck to buy home and I receive when the truck are arrived, I received it sheriffs and built it.
The sheriff myself. It is my memoirable experience because I haven't built this shelves by myself and I'm not good at carbon.
I'm not a good carpenter.
So, if this, it was very hard by, I finally could build by myself. So I get confident in building a shares.
**** 修正答案
I'll talk about an experience where I bought a shelf at Ikea and built it.
At the end of the last year, I bought a shelf at Ikea.
Ikea is a furniture store that sells furniture at cost-effective prices and asks customers to take furniture and assemble it themselves.
I asked Ikea to deliver the shelf to my apartment by paying an extra cost, and built it by myself.
I hadn't assembled furniture until this experience, and didn't have confidence in doing it.
Thanks to an attached manual, I finally was able to assemble it by myself.
This is a memorable project because it allowed me to get confidence in assembling furniture.
*** CELPIP-General Practice Tests, Set 5, Practice Test 1
**** 答案
I will talk about a new and kind of food that I have experienced in the United States. And last year, I moved in the United States from Japan. And when I went to groceries, restore, I see many old memes there. And in Japan, IX all had received old memes in the grocery stores.
So I was very surprised and there are many kinds of old meals. So I asked a grocery store sellers and the best options and I and tried and I was still and poor the milks or heat and cut many various ways to cook.
**** 修正答案
Oatmeal is a new kind of food that I tried for the first time.
I moved to the U.S. from Japan last year.
When I was in Japan, I hadn't tried oatmeal because there were few grocery stores that sell oatmeal.
When I went to a grocery store near my apartment in the U.S., I found many types of oatmeal there.
I asked a seller which product was good for a first-time buyer, and I bought his recommendation.
I tried it at home, and found it was tasty.
I buy it once a week and try cooking it in various ways.
I pour milk over the oatmeal and have it with fruit.
** Task3
*** 対策
- 右側、左側をright,left-hand side of the picutureと表現する。handで修飾するとrightを「正しい」と誤解されない。
*** CELPIP-General Practice Tests, Set 4, Practice Test 1
**** 答案
Now, I see a zoo, and In the NC 3 door pins in a pool and three star tattoos, and stuff dressed in red touching.
Try to touch the nose over the two dolphins. And at background, I see a bridge and there are many and visitors working there.
And at now fog round left side. I'll keep dressed in yellow is trying to touch doorfin in other.
Dropping is different from the art, the two doors that I mentioned, and what, right side. About is on the man, dressing it.
**** 批評
***** 模範回答にある表現
- One with blond hair. 金髪がいる。
**** 修正答案
I see a zoo.
There are three dolphins in the pool.
There are also three staff members dressed in red on the right-hand side of the picture.
Two of them are raising their hands, and two dolphins are approaching them.
There is a blackbird perched on the shoulder of one of the staff members.
A dolphin is swimming near a child dressed in yellow on the left-hand side of the picture.
In the background, there is a bridge and visitors are walking on it.
*** CELPIP-General Practice Tests, Set 4, Practice Test 2
**** 答案
Speaking. Now I see a reception area, there is a two stock members dressed in blue, in the rules as a receptionist and a man and resting green is talking to stock members there on the right side, there is two elderly people on there because husband and wife, there have a seating on the chair.
And after front of the picture, there is man and woman. They are like a boyfriend and girlfriend, and they are talking. And back at the background of this picture, there is a washroom and a little girl is entering to our ladies washrooms. And on the left side, there is a couch and a mang is reading a newspaper by and sitting the couch.
**** 修正答案
I see a reception in a building.
There are two receptionists.
A man in blue is talking to a receptionist.
A woman in pink is also talking to the other receptionist.
Her daughter is pulling her mother's hand.
In the background, there are rest rooms.
A girl is entering to a rest room.
There are two elderly people seated on chairs at left-hand side.
One is a male and is reading a newspaper.
The other is a woman who is drinking coffee.
*** CELPIP-General Practice Tests, Set 5, Practice Test 1
**** 修正答案
I see the sea in the picture.
There is a beach in front of this picture.
There is a sandcastle with three red flags.

I see a big wave on the right-hand side, and a man dressed in black is riding on the wave.
He is using a red surfboard.
I see a brown canoe under the wave. There are three people on the canoe, and they are paddling the canoe.

I see a parachute on the left-hand side that is pulled by a white boat.
I see three surfboards on the left-hand side.
The colors are blue, yellow, and white.
A man dressed in green is on the white one, and he holds a paddle.

** Task4
*** 対策
*** CELPIP-General Practice Tests, Set 4, Practice Test 1
**** 回答
I think a bird on the shoulder of a staffed dressed in red is going to fly and I'll dolphin.
That is trying to touch the hand of the man with a yellow color. Here is going to touch and she's hand.
And a dolphin is a crossing to map cheat dressed in yellow.
We are touched the hand of the kid and our, I see a A monkey character at the bree on the bridge.
And we he's holding a balloons and he will give those bearings to kids crossing to him and other visitors are crossing the
**** 修正答案
I think the two dolphins will swim in the pool after they touch the hands of the two staff members.
The bird on the shoulder of another staff member will fly away.
The child on the left-hand side of the picture will fall into the pool, and then his mother will help him.
The dolphin that is near the child will be surprised by the fall and swim away.
The staff member who has balloons will give them to the two children who are near him.
A man who is holding a dolphin balloon will give the balloon to a
child who is raising his hand.
*** CELPIP-General Practice Tests, Set 4, Practice Test 2
**** 回答
I think a girl of who is trying to entering a washroom, we enter the washroom and only get out and from the washroom afterward and the two elderly people on the left side are right side will stand up and go anything else press and a boyfriend and girlfriend in the front of the picture will go outside of this picture and mom dressed in green with no.
What, where should she should go, and leave the reception area and our
woman and dressed in purple at the receptionist who are talking with
receptionist, we missed also, get where she should go and leave this
reception area and mom
**** 修正答案
A man in green who is talking to a receptionist will leave this reception after the receptionist provides directions. 
A girl who is standing near a restroom will enter the room.
The daughter in cyan who is pulling her mother's hand will find a girl in yellow who is waving one of her hands.
They will start talking to each other.
A boyfriend and a girlfriend facing each other, will leave the building.
*** CELPIP-General Practice Tests, Set 5, Practice Test 1
**** 修正答案
I think most of the boats and surfboards will flip, and people on them may fall off into the sea due to the size of the big wave.
The man dressed in black on the top of the big wave may land unsafely.
The people on the wooden canoe may be in great danger because they are directly in the path of the wave.
The wave will destroy the sandcastle on the beach.
On the other hand, the man dressed in green, who is using a green surfboard, may be able to escape from the wave because he is near the beach.
Some surfboards on the left-hand side will not flip but will ride the wave , as they are far from its center.
** Task5
*** 対策
- 選択をselectionではなく、my preferenceで表現する。
*** CELPIP-General Practice Tests, Set 4, Practice Test 1
**** 回答
I think the model single office that I chose is prefer to original the original single office you selected because my my selection the most modern single office is the rent of this. It is cheaper than yours and there is no one a software and coffee tables. We can use it in them.00:31
When I we hold a meeting and but you are we cannot do. Hold the meeting with by far with furniture in if I be select your selections. And now, there are shares and storage spaces. We can put documents there. And,
**** 修正答案
I prefer the Modern Single Office to the Original Single Office.
I have a couple of reasons.
First, the rent of the Modern Single Office is lower by $100 than that of the Original Single Office.
We can save money if we choose my preference instead.
Second, there is a couch and a table in the Modern Single Office.
We can hold a meeting on them.
If we choose the Original Single Office, we would have to spend money on purchasing furniture.
Third, there is a shelf in the Modern Single Office.
As we have a lot of documents, we have to keep them in order.
We can use the shelf to place the documents.
Fourth, there is a workstation. It looks comfortable. I would be able to concentrate on my work if I use it.
There are no grammatical errors in the text. All the sentences are grammatically correct.

*** CELPIP-General Practice Tests, Set 4, Practice Test 2
**** 回答
Now I think Aubank grocery store. Gift cards is preferable than the bungee jump coupon and what I have a couple of reasons. First, if the we need every people need by something at the grocery store to leave. But and so it is the grocery store gift card is Essential for many people's on the other hand job, bungee jump.
Does some people does not write bungee jump and and no, I think the such coupon are not always make people happy any and they, and people have to pay a 100 Canadian dollars when the radio this activity but this
**** 修正答案
I think the grocery store gift card is preferable to bungee jumping coupon.
I have a few reasons.

First, shopping at grocery stores is essential for us while bungee jumping is not.
We should select a modest gift to make all the employees happy.
Some people like bungee jumping, others don't.
We also have to consider people who are unable to enjoy bungee jumping due to their disabilities.

Secondly, employees don't have to pay an extra cost when they use the gift card since it is a gift card.
On the other hand, bungee jumping with the discount coupon still costs $100.

Thirdly, the gift card won't expire. we can use them anytime.
*** CELPIP-General Practice Tests, Set 5, Practice Test 1
**** 修正答案
I think the park is more suitable than the pool.
I have several reasons.

First, the purpose of this activity is team building, and all the members must enjoy it.
Some employees don't have swimsuits.
Moreover, there may be people who cannot swim.
They would have to buy swimsuits or learn at swim if we choose the pool.
This doesn't allow people to enjoy team building.

Second, if it rains during the activity, we cannot continue to swim in the pool and have to stop the activity.
On the other hand, there is shelter in the park. 
We can continue team building in the shelter even if it rains.

Third, having the activity in the park is cost-effective compared to using the pool.
We have to pay fees to use the pool.
** Task6
*** 対策
- CELPIP-General Practice Tests, Set 4, Practice Test 1では、校長に話
  かける言い方ではなく、発表する言い方だった。
*** CELPIP-General Practice Tests, Set 4, Practice Test 1
**** 回答
I will sell, I will choose the first options high the school principal I should, you should, I think you should arrow allow the teams to attend the soccer match and pay. Money to do that. I think it is. This experiment is a good for educations of the, our soccer teams and if they win the soccer match, our, I think there Many and children who are interested in soccer want to attend enter, enter our high school and ultimately we can get our money.
**** 修正答案
I think we should allow our soccer team to compete in the national soccer match held in another province.

Here are a couple of reasons.
First, they can learn new techniques through the match whether they win or lose the match.
Second, if our team wins the match, our school will become more popular.
We can expect the number of applications to increase next year.
If we can't afford the cost, we should ask another sports teams like basketball and tennis to share some of their budgets.
If they accept the request, we will have the soccer team share some of their budget with them next year.
*** CELPIP-General Practice Tests, Set 4, Practice Test 2
**** 回答
I will choose the second options are Samaster. I'm afraid to say that I cannot help you moving because on the same day, I have to help Danny to finish his projects because if he did not success, our finish the project he would be fired. So to I have to, I want to help him.
I will remember that I have, I say that help you your moving, but I cannot do that and to compensate for it and could you already schedule in the moving and I will ask Danny to help you and And let's have a dinner with that him.
**** 修正答案
Samantha, I'm afraid to say that I cannot help your moving this weekend because I have to help Denny, who is a colleague, meet the deadline for a project.
If I did not help him, he would be fired.
I would like to help him to prevent him from resigning.
Could you reschedule your moving date to another day so that I can help you?
If you need an extra cost to reschedule, I'll pay for it.
I also ask Denny to help you.
*** CELPIP-General Practice Tests, Set 5, Practice Test 1
**** 修正答案
I will choose the second option.
I'm afraid to say that I can't help you as an account because my company doesn't allow employees to work as accountants for other organizations.
The policy applies not only to companies but also to non-profit organizations.
If I violate the policy, I will be fired.

I respect you for working in the organization, and want to help you as much as possible.
I will look for other accountants who work for different firms, and introduce them to you.
** Task7
*** 対策
*** CELPIP-General Practice Tests, Set 4, Practice Test 1
**** 回答
I think social media should require users to verify their true identity if I've that is because if users can send the message or express opinion without identifying Himself or herself, they can be a very offensive. I think it is not good for their platform and also and the users.00:43
And so that this is the main reason why they should the platform should ask users to verify their and to identity. And01:01
I think it is a good for you users to buy and if they express or posting a meaningful message of photograph, I think other people are respect them, so it is worth identifying their names. Oh, for the users too.
**** 修正答案
I think social media should require users to verify their real identity.

I have a couple of reasons.

As other people cannot identify them by their names, they may post offensive content.
If offensive content causes trouble, what they have to do is just create a new account.
Allowing anonymous users may not benefit social platforms.

Secondly, making users' identities disclosed to public can motivate users to post meaningful content.
By posting good messages with their own names, they become popular and are recognized.
Good content can make the platform more popular as well.

Third, users can use others' identities when posting content on social media. If social media doesn't require clarification of user identities, then anyone can use others' identities when posting content on it.
*** CELPIP-General Practice Tests, Set 4, Practice Test 2
**** 修正答案
I believe both parents should go out to work.
I have a few reasons.

Firstly, providing a good education to children requires a lot of money.
If both parents work, they can earn money more effectively than if only one parent works.

Second, If both parents are not in their home, their children can have opportunities to learn various things to become independent themselves.

Third, going out to work while their children are young can keep the parent's careers competitive with others.
Even if they stop going out to work while their children are little, they would have to resume working after their children grow up.
Having work experience while their children are young can be beneficial in getting a promotion or finding a new job later on.
*** CELPIP-General Practice Tests, Set 5, Practice Test 1
**** 修正答案
I think learning a subject online is more effective.
I have several reasons.

First, if I learn a subject online, I can save time to travel to a classroom.
I can spend more time on learning a subject online than on learning in a face-to-face classroom by saving the moving time.

Second, if I encounter something specific that I can't understand while learning a subject online, I can stop the video and repeat it until I understand it.
Students can adjust the speed of an online lecture to suit themselves.

Third, generally speaking, learning a subject online is more inexpensive than learning in a face-to-face classroom.
** Task8
*** CELPIP-General Practice Tests, Set 4, Practice Test 1
**** 回答
Interesting animal by road. This it is the cara of it is a brown. It looks a small thing pig but it is not fat and it is injured. It whereas a white turkey style with his our right hand and there it has a long three and nails for each hand and it has a long ears like peak.00:45
And there it it's not nose is looks like that of pig too. The color of the eye is a black and it is very small and he's trying to
**** 修正答案
I see an unusual animal beside a road.
It looks like a small, thin pig.
Its color is pink and it is dirty.
It is wearing bandage on its right arm.
It must be injured.
It has three long nails on each paw.
It has four nails on each leg.
It has a long tail.
Its ears and nose look like those of pigs.
The color of its eyes is black.
It is going to eat chips.

*** CELPIP-General Practice Tests, Set 4, Practice Test 1
**** 回答
King. Now all I seeing a buck weird and there are five old people at the back where and they do the strange things I own. There are attaching a kayak to the tree and trying to Make the kayak like a hammock by with a cup of some rope and think in this is very strange and because if they want to create a hammer, they should just or buy a handbook with, without using a kayak.
So this is the main reason why I think it is very strange, and three people talk just talking and they heated, do not help to other two people, but who are trying to get attached kayak to tree And,
**** 修正答案
**** Hello, I see a backyard where there is a group of five teenagers.
 Three of them are talking to each other while the other two are hanging a red boat between two trees.
 A woman on a ladder is tying a yellow rope to hang the boat from the trees.
 I think it looks strange because they should buy a hammock instead of hanging the boat.
 The boat looks heavy, and if they hang it, the trees might break.
 They are deliberately doing unsafe things.

*** C
**** 修正答案
This is your uncle.

I see there are four children in a field.
They are engaged in playing an interesting activity, and I'm calling you to ask whether you would like to participate in their activity.
They are preparing balloons.

A man dressed in green is making a stand on which they will put candles.
A man dressed in orange is holding a yellow balloon.
I think they will put a candle on the stand, and they will cover the stand with the yellow balloon.
There are two children behind the boys.
They are holding a purple balloon.
I see light inside the purple balloon.
If they stop holding the balloon, the balloon will fly away.

If you find it interesting, I will ask them to allow you to participate in their activity.
